// designs/legacy/mock_project/components/Sidebar.tsx
import { useState } from 'react';
import { Menu, FileText, Plus, Settings, Trash2, User } from 'lucide-react';
import { motion } from 'motion/react';
import { Button } from './ui/button';
import { Separator } from './ui/separator';
import { Popover, PopoverContent, PopoverTrigger } from './ui/popover';
import { Switch } from './ui/switch';
import { Label } from './ui/label';
import logo from 'figma:asset/3706fa20da8044023447a4700332f2d0ecb2a488.png';

export interface FileItem {
	id: string;
	name: string;
}

interface SidebarProps {
	files: FileItem[];
	activeFileId: string;
	onNewFile: () => void;
	onFileSelect: (fileId: string) => void;
	onDeleteFile: (fileId: string) => void;
}

export function Sidebar({
	files,
	activeFileId,
	onNewFile,
	onFileSelect,
	onDeleteFile
}: SidebarProps) {
	const [isExpanded, setIsExpanded] = useState(false);
	const [autoSave, setAutoSave] = useState(false);
	const [darkTheme, setDarkTheme] = useState(true);
	const [lineNumbers, setLineNumbers] = useState(true);
	const [popoverOpen, setPopoverOpen] = useState(false);

	const handleToggle = () => {
		setIsExpanded(!isExpanded);
	};

	return (
		<div
			className={`flex h-screen flex-col overflow-hidden bg-zinc-900 text-zinc-100 transition-all duration-300 ${
				isExpanded ? 'w-56' : 'w-12'
			}`}
		>
			{/* Hamburger Menu and Title */}
			<div className="relative flex h-12 items-center p-1">
				<Button
					variant="ghost"
					size="icon"
					className="flex-shrink-0 text-zinc-400 hover:bg-zinc-800 hover:text-zinc-100"
					onClick={handleToggle}
				>
					<Menu className="h-5 w-5" />
				</Button>

				<span
					className={`pointer-events-none absolute right-0 left-0 text-center whitespace-nowrap text-zinc-100 transition-opacity duration-300 ${isExpanded ? 'opacity-100' : 'opacity-0'}`}
					style={{
						fontFamily: "'Lato', Arial, sans-serif",
						fontWeight: 700,
						fontSize: '1.2rem'
					}}
				>
					Tonguetoquill
				</span>
			</div>

			{/* Logo centered below */}
			<div className="relative flex h-12 items-center justify-center overflow-hidden">
				<img src={logo} alt="Tonguetoquill Logo" className="h-8 flex-shrink-0" />
			</div>

			<Separator className="bg-zinc-700" />

			{/* Menu Items */}
			<div className="flex-1 overflow-y-auto p-2">
				<div className="space-y-1">
					<Button
						variant="ghost"
						className="w-full justify-start text-zinc-300 hover:bg-zinc-800 hover:text-zinc-100"
						onClick={onNewFile}
					>
						<Plus className="mr-2 h-4 w-4 flex-shrink-0" />
						{isExpanded && (
							<span className="animate-in fade-in transition-opacity duration-300">New File</span>
						)}
					</Button>

					{files.length > 0 && isExpanded && (
						<>
							<Separator className="my-2 bg-zinc-700" />
							{files.map((file) => (
								<div
									key={file.id}
									className={`group -mr-2 flex items-center gap-1 rounded pr-2 pl-2 ${
										file.id === activeFileId ? 'bg-zinc-700' : 'hover:bg-zinc-800'
									}`}
								>
									<Button
										variant="ghost"
										className={`flex-1 justify-start text-sm hover:bg-transparent ${
											file.id === activeFileId
												? 'text-zinc-100'
												: 'text-zinc-400 hover:text-zinc-100'
										}`}
										onClick={() => onFileSelect(file.id)}
									>
										<FileText className="mr-2 h-4 w-4 flex-shrink-0" />
										<span className="animate-in fade-in truncate transition-opacity duration-300">
											{file.name}
										</span>
									</Button>
									<Button
										variant="ghost"
										size="icon"
										className="h-8 w-8 flex-shrink-0 text-zinc-500 opacity-0 group-hover:opacity-100 hover:bg-transparent hover:text-red-400"
										onClick={(e) => {
											e.stopPropagation();
											onDeleteFile(file.id);
										}}
									>
										<Trash2 className="h-4 w-4" />
									</Button>
								</div>
							))}
						</>
					)}
				</div>
			</div>

			{/* User Profile and Settings Section */}
			<div className="space-y-1 border-t border-zinc-700 p-2">
				{/* User Profile Button */}
				<Button
					variant="ghost"
					className="w-full justify-start text-zinc-400 hover:bg-zinc-800 hover:text-zinc-100"
				>
					<User className="mr-2 h-5 w-5 flex-shrink-0" />
					{isExpanded && (
						<span className="animate-in fade-in transition-opacity duration-300">Profile</span>
					)}
				</Button>

				{/* Settings Gear Button */}
				<Popover open={popoverOpen} onOpenChange={setPopoverOpen}>
					<PopoverTrigger asChild>
						<Button
							variant="ghost"
							className="w-full justify-start text-zinc-400 hover:bg-zinc-800 hover:text-zinc-100"
						>
							<Settings className="mr-2 h-5 w-5 flex-shrink-0" />
							{isExpanded && (
								<span className="animate-in fade-in transition-opacity duration-300">Settings</span>
							)}
						</Button>
					</PopoverTrigger>
					<PopoverContent
						side="right"
						align="end"
						className="w-64 border-zinc-700 bg-zinc-800 p-0 text-zinc-100"
					>
						<div className="p-4">
							<h3 className="mb-4">Settings</h3>

							<div className="space-y-4">
								<div className="flex items-center justify-between">
									<Label htmlFor="auto-save" className="text-zinc-300">
										Auto-save
									</Label>
									<Switch id="auto-save" checked={autoSave} onCheckedChange={setAutoSave} />
								</div>

								<div className="flex items-center justify-between">
									<Label htmlFor="dark-theme" className="text-zinc-300">
										Dark Theme
									</Label>
									<Switch id="dark-theme" checked={darkTheme} onCheckedChange={setDarkTheme} />
								</div>

								<div className="flex items-center justify-between">
									<Label htmlFor="line-numbers" className="text-zinc-300">
										Line Numbers
									</Label>
									<Switch
										id="line-numbers"
										checked={lineNumbers}
										onCheckedChange={setLineNumbers}
									/>
								</div>
							</div>
						</div>
					</PopoverContent>
				</Popover>
			</div>
		</div>
	);
}

// src/lib/components/Sidebar/Sidebar.svelte
<script lang="ts">
	import { Menu, SquarePen, Settings, User } from 'lucide-svelte';
	import Button from '$lib/components/ui/button.svelte';
	import { SidebarButtonSlot } from '$lib/components/Sidebar';
	import { DocumentListItem } from '$lib/components/DocumentList';
	import Separator from '$lib/components/ui/separator.svelte';
	import Popover from '$lib/components/ui/popover.svelte';
	import PopoverTrigger from '$lib/components/ui/popover-trigger.svelte';
	import PopoverContent from '$lib/components/ui/popover-content.svelte';
	import Switch from '$lib/components/ui/switch.svelte';
	import Label from '$lib/components/ui/label.svelte';
	import Sheet from '$lib/components/ui/sheet.svelte';
	import SheetTrigger from '$lib/components/ui/sheet-trigger.svelte';
	import SheetContent from '$lib/components/ui/sheet-content.svelte';
	import { Root as Dialog, Portal, Close } from '$lib/components/ui/dialog.svelte';
	import DialogContent from '$lib/components/ui/dialog-content.svelte';
	import DialogHeader from '$lib/components/ui/dialog-header.svelte';
	import DialogTitle from '$lib/components/ui/dialog-title.svelte';
	import DialogDescription from '$lib/components/ui/dialog-description.svelte';
	import DialogFooter from '$lib/components/ui/dialog-footer.svelte';
	import { documentStore } from '$lib/stores/documents.svelte';
	import { onMount } from 'svelte';

	type SidebarProps = {
		user?: { email: string; id: string } | null;
	};

	let { user }: SidebarProps = $props();

	let isExpanded = $state(false);
	let autoSave = $state(true);
	let lineNumbers = $state(true);
	let popoverOpen = $state(false);
	let mobileSheetOpen = $state(false);
	let isMobile = $state(false);
	let deleteDialogOpen = $state(false);
	let documentToDelete = $state<string | null>(null);
	let isDarkMode = $state(true);

	onMount(() => {
		// Load dark mode preference from localStorage
		const savedDarkMode = localStorage.getItem('dark-mode');
		if (savedDarkMode !== null) {
			isDarkMode = savedDarkMode === 'true';
		}
		// Apply dark mode class to document
		updateDarkMode(isDarkMode);

		// Check if sidebar should be expanded from localStorage
		const savedExpanded = localStorage.getItem('sidebar-expanded');
		if (savedExpanded !== null) {
			isExpanded = savedExpanded === 'true';
		}

		// Load settings from localStorage
		const savedAutoSave = localStorage.getItem('auto-save');
		if (savedAutoSave !== null) {
			autoSave = savedAutoSave === 'true';
		}

		const savedLineNumbers = localStorage.getItem('line-numbers');
		if (savedLineNumbers !== null) {
			lineNumbers = savedLineNumbers === 'true';
		}

		// Check if mobile
		const checkMobile = () => {
			isMobile = window.innerWidth < 1024;
		};
		checkMobile();
		window.addEventListener('resize', checkMobile);

		return () => {
			window.removeEventListener('resize', checkMobile);
		};
	});

	function handleToggle() {
		isExpanded = !isExpanded;
		localStorage.setItem('sidebar-expanded', isExpanded.toString());
	}

	function handleNewFile() {
		documentStore.createDocument();
		// Close mobile sheet after creating file
		if (isMobile) {
			mobileSheetOpen = false;
		}
	}

	function handleFileSelect(fileId: string) {
		documentStore.setActiveDocumentId(fileId);
		// Close mobile sheet after selecting file
		if (isMobile) {
			mobileSheetOpen = false;
		}
	}

	function handleDeleteFile(fileId: string) {
		if (documentStore.documents.length === 1) {
			// Can't delete the last file
			return;
		}
		// Show confirmation dialog
		documentToDelete = fileId;
		deleteDialogOpen = true;
	}

	function confirmDelete() {
		if (documentToDelete) {
			documentStore.deleteDocument(documentToDelete);
			documentToDelete = null;
		}
		deleteDialogOpen = false;
	}

	function cancelDelete() {
		documentToDelete = null;
		deleteDialogOpen = false;
	}

	function handleAutoSaveChange(value: boolean) {
		autoSave = value;
		localStorage.setItem('auto-save', value.toString());
		// Dispatch storage event manually for same-tab communication
		window.dispatchEvent(
			new StorageEvent('storage', {
				key: 'auto-save',
				newValue: value.toString(),
				oldValue: (!value).toString(),
				url: window.location.href,
				storageArea: localStorage
			})
		);
	}

	function handleLineNumbersChange(value: boolean) {
		lineNumbers = value;
		localStorage.setItem('line-numbers', value.toString());
		// Dispatch storage event manually for same-tab communication
		window.dispatchEvent(
			new StorageEvent('storage', {
				key: 'line-numbers',
				newValue: value.toString(),
				oldValue: (!value).toString(),
				url: window.location.href,
				storageArea: localStorage
			})
		);
	}

	function updateDarkMode(dark: boolean) {
		if (dark) {
			document.documentElement.classList.add('dark');
		} else {
			document.documentElement.classList.remove('dark');
		}
	}

	function handleDarkModeChange(value: boolean) {
		isDarkMode = value;
		localStorage.setItem('dark-mode', value.toString());
		updateDarkMode(value);
	}
</script>

{#snippet sidebarContent()}
	<!-- Hamburger Menu and Title -->
	<div class="relative flex items-center">
		<SidebarButtonSlot
			icon={Menu}
			{isExpanded}
			class="text-muted-foreground hover:bg-accent hover:text-foreground active:scale-95"
			onclick={handleToggle}
			ariaLabel={isExpanded ? 'Collapse sidebar' : 'Expand sidebar'}
		/>

		<span
			class="pointer-events-none absolute right-0 left-0 text-center font-mono text-lg whitespace-nowrap text-foreground italic transition-opacity duration-300 {isExpanded
				? 'opacity-100'
				: 'opacity-0'}"
		>
			Tonguetoquill
		</span>
	</div>

	<!-- Separator directly after hamburger/title so top border aligns with TopMenu -->
	<Separator class="bg-border" />

	<!-- Menu Items -->
	<div class="flex-1 overflow-hidden">
		<div>
			<SidebarButtonSlot
				icon={SquarePen}
				label="New File"
				{isExpanded}
				class="w-full justify-start overflow-hidden text-sm text-foreground/80 hover:bg-accent hover:text-foreground active:scale-[0.985]"
				onclick={handleNewFile}
				ariaLabel="Create new document"
			/>

			{#if !isExpanded}
				<Separator class="bg-border" />
			{/if}

			{#if documentStore.documents.length > 0 && isExpanded}
				<Separator class="bg-border" />

				<!-- Recents Section Header -->
				<div
					class="sticky top-0 z-10 mt-1 bg-gradient-to-b from-background from-50% to-background/40 pb-2 pl-2"
				>
					<h3 class="text-xs text-muted-foreground">Recents</h3>
				</div>

				<!-- Scrollable Recent Items -->
				<div
					class="space-y-px overflow-x-hidden overflow-y-auto"
					style="max-height: calc(100vh - 300px);"
				>
					{#each documentStore.documents as doc (doc.id)}
						<DocumentListItem
							document={doc}
							isActive={doc.id === documentStore.activeDocumentId}
							onSelect={handleFileSelect}
							onDelete={handleDeleteFile}
						/>
					{/each}

					<!-- Bottom gradient fade -->
					<div
						class="pointer-events-none sticky bottom-0 h-4 bg-gradient-to-t from-background to-transparent"
					></div>
				</div>
			{/if}
		</div>
	</div>

	<!-- User Profile and Settings Section -->
	<div class="space-y-1 border-t border-border">
		<!-- User Profile Button -->
		{#if user}
			<SidebarButtonSlot
				icon={User}
				label={user.email}
				{isExpanded}
				class="w-full justify-start overflow-hidden text-sm text-muted-foreground hover:bg-accent hover:text-foreground active:scale-[0.985]"
				title={user.email}
				ariaLabel="User profile: {user.email}"
			/>
		{/if}

		<!-- Settings Gear Button -->
		<div class="sidebar-button-slot">
			<Popover bind:open={popoverOpen}>
				{#snippet children()}
					<PopoverTrigger
						class="sidebar-slot-button {isExpanded
							? 'sidebar-slot-button-full'
							: ''} inline-flex items-center overflow-hidden rounded-md text-sm font-medium whitespace-nowrap text-muted-foreground transition-transform hover:bg-accent hover:text-foreground focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 focus-visible:outline-none active:scale-[0.985] disabled:pointer-events-none disabled:opacity-50"
					>
						{#snippet children()}
							<Settings class="sidebar-icon" />
							{#if isExpanded}
								<span>Settings</span>
							{/if}
						{/snippet}
					</PopoverTrigger>
					<PopoverContent
						side="right"
						align="end"
						class="w-64 border-border bg-surface-elevated p-0 text-foreground"
					>
						{#snippet children()}
							<div class="p-4">
								<h3 class="mb-4 text-lg font-semibold">Settings</h3>

								<div class="space-y-4">
									<div class="flex items-center justify-between">
										<Label for="dark-mode" class="text-foreground/80">
											{#snippet children()}
												Dark Mode
											{/snippet}
										</Label>
										<Switch
											id="dark-mode"
											bind:checked={isDarkMode}
											onCheckedChange={handleDarkModeChange}
										/>
									</div>

									<Separator class="my-3 bg-border" />

									<div class="flex items-center justify-between">
										<Label for="auto-save" class="text-foreground/80">
											{#snippet children()}
												Auto-save
											{/snippet}
										</Label>
										<Switch
											id="auto-save"
											bind:checked={autoSave}
											onCheckedChange={handleAutoSaveChange}
										/>
									</div>

									<div class="flex items-center justify-between">
										<Label for="line-numbers" class="text-foreground/80">
											{#snippet children()}
												Line Numbers
											{/snippet}
										</Label>
										<Switch
											id="line-numbers"
											bind:checked={lineNumbers}
											onCheckedChange={handleLineNumbersChange}
										/>
									</div>
								</div>
							</div>
						{/snippet}
					</PopoverContent>
				{/snippet}
			</Popover>
		</div>
	</div>
{/snippet}

{#if isMobile}
	<!-- Mobile Sheet -->
	<div>
		<Sheet bind:open={mobileSheetOpen}>
			{#snippet children()}
				<SheetTrigger>
					{#snippet children()}
						<Button
							variant="ghost"
							size="icon"
							class="fixed top-2 left-2 z-40 text-muted-foreground hover:bg-accent hover:text-foreground lg:hidden"
						>
							{#snippet children()}
								<Menu class="h-5 w-5" />
							{/snippet}
						</Button>
					{/snippet}
				</SheetTrigger>
				<SheetContent side="left" class="flex w-72 flex-col bg-background p-0 text-foreground">
					{#snippet children()}
						{@render sidebarContent()}
					{/snippet}
				</SheetContent>
			{/snippet}
		</Sheet>
	</div>
{:else}
	<!-- Desktop Sidebar -->
	<div
		class="flex h-screen flex-col overflow-hidden border-r border-border bg-background text-foreground transition-all duration-300"
		style="width: {isExpanded
			? 'var(--sidebar-expanded-width)'
			: 'var(--sidebar-collapsed-width)'}; transition-timing-function: cubic-bezier(0.165, 0.85, 0.45, 1);"
	>
		{@render sidebarContent()}
	</div>
{/if}

<!-- Delete Confirmation Dialog -->
<Dialog bind:open={deleteDialogOpen}>
	{#snippet children()}
		<DialogContent>
			{#snippet children()}
				<DialogHeader>
					{#snippet children()}
						<DialogTitle>
							{#snippet children()}
								Delete Document
							{/snippet}
						</DialogTitle>
						<DialogDescription>
							{#snippet children()}
								Are you sure you want to delete this document? This action cannot be undone.
							{/snippet}
						</DialogDescription>
					{/snippet}
				</DialogHeader>
				<DialogFooter>
					{#snippet children()}
						<Button
							variant="ghost"
							size="sm"
							class="text-muted-foreground hover:bg-accent hover:text-foreground"
							onclick={cancelDelete}
						>
							{#snippet children()}
								Cancel
							{/snippet}
						</Button>
						<Button
							variant="default"
							size="sm"
							class="bg-red-600 text-white hover:bg-red-700"
							onclick={confirmDelete}
						>
							{#snippet children()}
								Delete
							{/snippet}
						</Button>
					{/snippet}
				</DialogFooter>
			{/snippet}
		</DialogContent>
	{/snippet}
</Dialog>

<style>
	:global(.sidebar-icon) {
		width: var(--sidebar-icon-size);
		height: var(--sidebar-icon-size);
		flex-shrink: 0;
	}

	:global(.sidebar-icon:has(+ *)) {
		margin-right: 0.5rem;
	}

	:global(.sidebar-icon-small) {
		/* This calculates 60% of the parent's --sidebar-icon-size */
		width: calc(var(--sidebar-icon-size) * 0.6);
		height: calc(var(--sidebar-icon-size) * 0.6);
	}

	:global(.sidebar-section-height) {
		height: calc(var(--sidebar-button-size) + var(--sidebar-padding) * 2);
	}
</style>
